spring.application.name=demo
whatsapp.number=5562993436750

api.security.token.secret=minha-chave-secreta-dev-123456

cloudinary.cloud-name=dakymflxt
cloudinary.api-key=669394372918437
cloudinary.api-secret=XDrpZfq1oarT5VDcylR4lJLFKCI

spring.datasource.url=jdbc:postgresql://ep-shiny-pine-aqbtl1sn.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FMASp5ct3ZEh
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
